Cargo.lock, Cargo.toml, src/main.rs
These are my suggestions - they're all pretty minor however. The biggest one is just the use of Result + `?` in main - getting used to the rust style of error handling is pretty key since it's pretty pervasive.
=> Rust code looks pretty good - minor nits

LICENSE, README.md, src/main.rs, src/templates.rs, src/types.rs
Refactor just a tiny bit into types.rs and templates.rs files for easier reading, and a license and README in preparation for using the tool internally. No functionality changes yet, can add testing and stuff later.
Test plan:
cargo build and cargo run still work
=> Refactor, add LICENSE and README

Cargo.lock, Cargo.toml, src/cli.rs, src/lib.rs
- Ran clippy on the files for a quick lint
- Decoupled some of the CLI from the library. The only part that's still a bit tangled up is the spinner, but I'll deal with that later 
- Defined a lib.rs, deleted the Cargo.lock file that's generated and added to gitignore. Building the binary (with `cargo run` or `cargo build --bin tlparse`) still results in an executable binary, but the library is now the main crate. 
TODO: need to test what happens with pip and cargo install
=> Libify tlparse, first steps

src/lib.rs, src/parsers.rs, src/types.rs
This PR tries to generalize structured log parsers to make it easier to add new analyses for people less familiar with tlparse internals. This also makes it easier for us to have internal only analyses later. 
Basic design:
All analyses implement a trait called StructuredLogParser. To implement a new parser, simply implement the trait with:
- A function that extracts the Metadata out of the Envelope 
- A function that, given your specific Metadata and other information, produces an output vec
Afterwards, just add the trait to `all_parsers`.
I've gone ahead and implemented the simpler ones quickly and will do the rest in a bit. I know it looks like a bunch of boilerplate with lifetimes (needing to track the lifetime of the envelope each parser is associated with, for example), but honestly …
=> Generalize structured log parsers

src/lib.rs
=> Use FxIndexMap to ensure build products are sorted chronologically

src/lib.rs, src/templates.rs, src/types.rs
Here's what it looks like:
Notice that the backward products show up in reverse order.
=> Add ordinal indicating what order products appeared in logs

src/lib.rs, src/parsers.rs, src/templates.rs, src/types.rs
Companion PR https://github.com/pytorch/pytorch/pull/124648
=> Add parsing for aot_autograd_backward_compilation_metrics

src/cli.rs, src/lib.rs
=> Add --strict-compile-id for compile id presence testing

src/lib.rs, src/types.rs
There's a bug in our current frame emission code where we emit three
Dynamo frames.  Actually, I think this is fixed in PyTorch main but
there's legacy code still running it.  Chop it off.
=> Remove unnecessary stack frame suffix

.gitignore, README.md, src/lib.rs, src/parsers.rs, src/templates.rs, src/types.rs, tests/inputs/links.log
Generalize parsers so that they can output either a file or a URL. URLs don't appear in the ParseOutput that parse_path returns, but they do appear in the compile directory.
=> Add functionality for structured logs to render links in tlparse

src/lib.rs, src/parsers.rs, src/templates.rs, src/types.rs
With the changes to make tlparse artifacts unique, we also made it a bit harder to link to compilation artifacts from pages other than index.html. This change factors out compilationmetrics so that you can pass the entire directory into tlparse, so that each compilation metrics page wlil have all of the build products associated with that compile id directly linked. 
It also allows the failures and restarts page to link correctly to the compilation metrics page, using a similar technique.
It's a bit hacky how I derive the filenames for compilation_metrics.html, but I couldn't really come up with that good of a way otherwise. We might wanna refactor later so that each file has a unique id associated with it in the FXIndexMap or something.
=> Fix links, dump all output files in compilation metrics page

src/lib.rs, src/parsers.rs, src/templates.rs, src/types.rs
Includes linkifying stack frames
=> Add dump_file parsing support

src/lib.rs, src/parsers.rs, src/templates.rs, src/types.rs, tests/integration_test.rs
Internally we can probably `s/https://ui.perfetto.dev/<internal link>` 
For now we will have one trace for the entire tlparse: there are certain dynamo_timed events that occur outside of compile contexts i.e. cudagraphify and autotuning, which occur at "runtime", and having them in separate compile contexts actually makes the data incomplete. If this turns out to make traces too large we can reconsider some other format
=> Add support for parsing chromium_events

src/lib.rs
If the rank is different, we try to skip the row in the tlparse, but we need to consume the attached payload first, or else the payload will fail to parse as a new line.
=> Parse payload before potentially skipping

src/cli.rs
Added the following:
- `tlparse --latest` to parse the most recently modified log in the working directory
- `tlparse [PATH] --latest` to parse the most recently modified log in the specified directory
Implements #43
=> Add --latest flag

src/parsers.rs, src/types.rs
Add `inductor_pre_grad_graph` tag for inductor provenance tracking. It dumps the input graph to `aot_compile`.
=> Add pre_grad_graph tag

src/templates.rs
Test Plan:
```
$ tlparse -o /tmp/foo --overwrite --no-browser --strict ~/tmp/trace_logs_slarsen/dedicated_log_torch_trace_l2k873uc.log
Detected rank: None
Parser compilation_metrics failed: Encountered rendering error on line 60, column 19. Reason: Expected an array for path 'm.compliant_custom_ops' but found a non-iterable value.
[00:00:00] [#############################################################################################################################################################################################] 133.30 KiB/133.30 KiB [22.37 MiB/s] (0s)
Stats { ok: 62, other_rank: 0, fail_glog: 0, fail_json: 0, fail_payload_md5: 0, fail_dynamo_guards_json: 0, fail_parser: 0, unknown: 0 } …
```
=> Allow for null compliant_custom_ops and null m.non_compliant_ops

src/lib.rs, src/parsers.rs, src/templates.rs, src/types.rs
Adding rendering of "guard_added_fast" on Compilation Metrics page.
Making Stack trees collapsible:
https://github.com/user-attachments/assets/df880917-5658-4508-96c4-e92518660b05
=> guard_added_fast rendering in compilation metrics

src/lib.rs, tests/inputs/cache_hit_miss.log
Title
`cargo run tests/inputs/cache_hit_miss.log --overwrite` works for aotautograd_hash_bypass
=> Allow any cache hit/miss/bypass to have emojis, not just fx_graph

src/lib.rs, tests/integration_test.rs
Adds a new JSON representation of the compile directory, which basically has a list of output artifacts by name. Here's what an example json would look like:
```
{
"[0/0]": {
"artifacts": [
{
"name": "dynamo_output_graph_0.txt",
"number": 0,
"suffix": "",
"url": "-_0_0_0/dynamo_output_graph_0.txt"
},
{
"name": "aot_forward_graph_1.txt",
"number": 1,
"suffix": "",
"url": "-_0_0_0/aot_forward_graph_1.txt"
},
{
"name": "fx_graph_cache_hash_2.json",
"number": 2,
"suffix": "",
"url": "-_0_0_0/fx_graph_cache_hash_2.json"
},
{
"name": "dynamo_guards_3.html",
"number": 3,
"suffix": "",
"url": "-_0_0_0/dynamo_guards_3.html"
},
{
"name": "dynamo_cpp_guards_str_4.txt",
"number": 4,
"suffix": "",
"url": "-_0_0_0/dynamo_cpp_guards_str_4.txt"
},
{
"name": "compilation_metrics_5.html",
"number": 5, …
```
=> Add compile_directory.json

src/lib.rs, tests/inputs/autotune_with_compile_id.log
Runtime autotuning compile ids don't have an attempt associated with them, which results in duplicate rows in the compile directory. This fixes this issue. 
This does *not* implement support for runtime_compilation_metrics, which I'll leave as a TODO for when we want to build support for that in tlparse. 
Added a new test log, along with the result, where we now see no duplicate [0/0]:
=> Support runtime compile ids which don't have an attempt

src/lib.rs
This makes it more robust to the case where two mapping jsons are produced.
=> In provenance tracking, process the last file instead of the first file

src/parsers.rs
We encountered an issue that TLParse failed to parse json string(probably because the json string was generated in python which has some discrepancy with Rust serde_json lib). This PR prevents failure by catching such error and fallback to use the raw payload when parsing failed.
=> [TLParse] Save raw string if failed to parse json string

src/lib.rs, src/provenance.css, src/provenance.html, src/provenance.js, tests/inputs/inductor_provenance_aot_cuda_log.txt, tests/inputs/inductor_provenance_aot_log.txt, tests/inputs/inductor_provenance_jit_cuda_log.txt, tests/inputs/inductor_provenance_jit_log.txt, tests/integration_test.rs
Update the file names used for provenance tracking due to changes in https://github.com/pytorch/pytorch/pull/153584/files#diff-e0cdb58c0f84f56f20c5433339b6d83c470dcde47847e2328effea6bedd4cd27
Additional changes:
- update the test log files
- Highlight the whole line
- Allow panel size changes
=> Update Provenance Tracking Name

src/lib.rs, src/parsers.rs, src/types.rs, tests/integration_test.rs
I used these claude code prompts:
- In src/lib.rs there is a main loop demarcated by ' while let Some((lineno, line)) = iter.next()' which processes every line in the input log file.  We currently try to directly parse out the JSON into our structs. I want to also directly re-dump the log line (metadata + JSON) (don't bother parsing it) to a file shortraw.log (analogous to raw.log, which has everything) but do NOT dump the payload. And then I want the payload to go to a folder payloads/HASH.txt (using the has_payload hash as the content-addressed key). Augment a test or two in the existing tests/ to check for the existence of shortraw.log and an appropriate number of lines.
- Let's add a new field to src/parser.rs which is PayloadFile which consists only of a PathBuf. Its semantics are …
=> Add raw.jsonl support.

src/lib.rs, src/templates.rs, src/types.rs
Basic Placeholder desync warning banner on TLParse Landing Page
In future, will use this component to display desync warnings.
=> Placeholder desync warning message on TLParse Landing Page

src/cli.rs, src/parsers.rs, src/types.rs, tests/inputs/multi_rank_schedule/dedicated_log_torch_trace_rank_0_6u3fubwl.log, tests/inputs/multi_rank_schedule/dedicated_log_torch_trace_rank_1_n8zycf07.log, tests/inputs/multi_rank_schedule/dedicated_log_torch_trace_rank_2.log, tests/integration_test.rs
- **New functionality**: Added `read_collective_schedules()` function to parse `inductor_collective_schedule*.json` files across multiple ranks
- **Multi-graph support**: Handles multiple compilation graphs per rank (different compile IDs like `-_0_0_0`, `-_1_0_0`, etc.)
- **JSON parsing**: Includes automatic fixing of trailing comma issues commonly found in these artifacts
- **Data structures**: Added `CollectiveSchedule` struct to represent parsed schedules with rank, graph ID, and operations list
- **Testing**: Added integration tests to verify multi-rank parsing functionality
Below is collective_schedules.json : aggregated from all ranks which will be used for diverging ranks based on collective ops order in future PRs
=> Add collective schedule parsing support for multi-rank PyTorch compilation artifacts

src/cli.rs, src/lib.rs, src/parsers.rs, src/templates.rs, src/types.rs, tests/inputs/multi_rank_runtime/dedicated_log_torch_trace_rank_0.log, tests/inputs/multi_rank_runtime/dedicated_log_torch_trace_rank_1.log, tests/inputs/multi_rank_runtime/dedicated_log_torch_trace_rank_2.log, tests/inputs/multi_rank_runtime/dedicated_log_torch_trace_rank_3.log, tests/inputs/multi_rank_runtime/dedicated_log_torch_trace_rank_4.log, tests/integration_test.rs
Summary:
- Generate chromium_trace_with_runtime.json from runtime estimations and add metadata so Perfetto shows:
- Processes: one per rank (pid = rank, name “Rank”)
- Threads: one per compiled graph within each rank, named “graph <graph_name>”
Users can pin specific graphs across ranks that they want to compare.
=> Add Chromium trace for runtime estimates (per-graph threads, per-rank processes)

src/lib.rs, src/provenance.html, src/provenance.js, src/types.rs, tests/inputs/inductor_provenance_aot_debug_handle_log.txt, tests/inputs/inductor_provenance_jit_debug_handle_log.txt, tests/integration_test.rs
- Move most of the javascript code to rust
- Prepare for the debug handle addition. If a kernel's name is in the format `{kernel_name}:{debug_handle}`, we use a separate logic to map the kernel name to line number. 
- Add more comprehensive testing
=> Refactor provenance tracking highlighter code

src/lib.rs, tests/integration_test.rs
What This PR Does
- Adds a new execution_order library module that parses graph execution sequences from PyTorch logs and detects divergences across ranks using existing collective schedule and cache analysis infrastructure.
Key Components
- parse_graph_execution_order(): Extracts compile_id sequences from graph_execution JSON artifacts
- analyze_execution_order(): Aligns ranks by execution index and flags ScheduleMismatch/CacheMismatch issues
- Structured reporting: In-memory ExecOrderReport with per-index divergence details
Integration
- Reuses existing read_collective_schedules() and cache analysis data
Next Steps
- Wire this analysis into --all-ranks-html landing page to display "Execution-Order Diagnostics" section when artifacts are present.
=> Add execution order divergence analysis library module

src/lib.rs, tests/integration_test.rs
=> Fix inductor provenance tracking bug when kernel name has multiple colons

src/lib.rs
Avoid highlighting variable assignment lines like " triton_poi_xnumel_1 = 1500L*s6;"
=> Further fix highlighting in inductor provenance tracking
