src/lib.rs, src/templates.rs, src/types.rs
=> Add a stack trie for unknown compile id compile sites

src/lib.rs, src/templates.rs, src/types.rs
=> Color code runs in the stack trie

src/lib.rs, src/parsers.rs, src/templates.rs, src/types.rs
=> Include stack in compilation metrics page

src/cli.rs, src/lib.rs, src/templates.rs, src/types.rs
=> Add --custom-header-html to add some extra test on page

src/lib.rs
=> CR for #24

src/cli.rs, src/lib.rs
=> Major bug fix: custom_header_html shouldn't be mandatory

src/lib.rs, src/parsers.rs, src/types.rs, tests/integration_test.rs
=> Avoid file clobber, adjust margin, cargo fmt

src/lib.rs, src/parsers.rs, src/templates.rs, src/types.rs
=> Render symbolic shape specialization

src/cli.rs, src/lib.rs, src/parsers.rs, src/types.rs
=> Add support for dynamo_cpp_guards_str, and some helpers for finding unrecognized fields

src/lib.rs, src/types.rs
=> Add structs for TensorDesc and co

src/templates.rs
=> Vertical align tables to top

src/lib.rs, src/templates.rs
=> Include original log file in outputs

src/lib.rs, src/parsers.rs, src/templates.rs, src/types.rs
=> Support bwd_compilation_metrics entries

src/cli.rs, src/lib.rs, src/parsers.rs
Fixes issue: https://github.com/ezyang/tlparse/issues/53
=> Add option for plain text Formatting

src/lib.rs, src/types.rs
=> Improve useless stack frame deletion algorithm more

src/lib.rs, src/parsers.rs, src/templates.rs, src/types.rs, tests/inputs/cache_hit_miss.log, tests/integration_test.rs
=> Add cache hit/miss/bypass suffix to index report

Cargo.lock, Cargo.toml
Include some generated changes from `cargo update`
=> Release 0.3.29

src/templates.rs
=> Handle edge case of URL hashes in query param script

tests/integration_test.rs
=> add test for inductor provenance tracking 

Cargo.lock, Cargo.toml
Update TLParse version to v0.4.1
=> release: v0.4.1
